Repository toor1245/MatrixDotNet, pull requests merged in 2020-11, with the labels that each got.

#9 optimize add and reduce column
  src/MatrixDotNet/Extensions/Conversion/MatrixConversionExtension.cs
  src/MatrixDotNet/Matrix.cs
  tests/MatrixDotNet.FunctionalTesting/BenchMatrix/BenchReduceColumn.cs
  tests/MatrixDotNet.UnitTesting/MatrixTests/MatrixConversionTest.cs
Labels: enhancement

#31 Add quadratic form
  .github/workflows/run_tests.yml
  src/MatrixDotNet.NetCore/MatrixAsFixedBuffer.cs
  src/MatrixDotNet.NetCore/Simd/AddMatrixSimd.cs
  src/MatrixDotNet.NetCore/Simd/CompareMatrixSimd.cs
  src/MatrixDotNet.NetCore/Simd/MultiplyMatrixSimd.cs
  src/MatrixDotNet.NetCore/Simd/Statistics/MaxMatrixSimd.cs
  src/MatrixDotNet.NetCore/Simd/Statistics/MinMatrixSimd.cs
  src/MatrixDotNet.NetCore/Simd/SumMatrixSimd.cs
  src/MatrixDotNet.sln.DotSettings
  src/MatrixDotNet/Extensions/Builder/MatrixIdentityExtension.cs
  src/MatrixDotNet/Extensions/Builder/MatrixMinorExtension.cs
  src/MatrixDotNet/Extensions/Conversion/MatrixCloneExtension.cs
  src/MatrixDotNet/Extensions/Conversion/MatrixConversionExtension.cs
  src/MatrixDotNet/Extensions/Criteries/DefiniteType.cs
  src/MatrixDotNet/Extensions/Criteries/SylvestersСriterion.cs
  src/MatrixDotNet/Extensions/Decompositions/MatrixCholeskyExtension.cs
  src/MatrixDotNet/Extensions/Decompositions/MatrixLUPExtension.cs
  src/MatrixDotNet/Extensions/Determinants/LUPDeterminant.cs
  src/MatrixDotNet/Extensions/Determinants/MinorDeterminant.cs
  src/MatrixDotNet/Extensions/MatrixOutputExtension.cs
  src/MatrixDotNet/Extensions/MatrixRankExtension.cs
  src/MatrixDotNet/Extensions/Options/ShellHelper.cs
  src/MatrixDotNet/Extensions/Options/Template.cs
  src/MatrixDotNet/Extensions/Options/TemplateHtml.cs
  src/MatrixDotNet/Extensions/Options/TemplateMarkdown.cs
  src/MatrixDotNet/Extensions/Performance/Operations/AddMatrixUnsafe.cs
  src/MatrixDotNet/Extensions/Performance/Operations/CompareMatrixUnsafe.cs
  src/MatrixDotNet/Extensions/Performance/Operations/MultiplyMatrixUnsafe.cs
  src/MatrixDotNet/Extensions/Performance/Operations/SubMatrixUnsafe.cs
  src/MatrixDotNet/Extensions/Statistics/Covariance.cs
  src/MatrixDotNet/Extensions/Statistics/Intervals.cs
  src/MatrixDotNet/Extensions/Statistics/TableSetup/ConfigIntervals.cs
  src/MatrixDotNet/Extensions/Statistics/TableSetup/ConfigVariations.cs
  src/MatrixDotNet/Extensions/Statistics/TableSetup/IConfig.cs
  src/MatrixDotNet/Extensions/Statistics/TableSetup/Setup.cs
  src/MatrixDotNet/Extensions/Statistics/TableSetup/SetupIntervals.cs
  src/MatrixDotNet/Extensions/Statistics/TableSetup/SetupVariations.cs
  src/MatrixDotNet/Extensions/Statistics/TableSetup/TableIntervals.cs
  src/MatrixDotNet/Extensions/Statistics/TableSetup/TableVariations.cs
  src/MatrixDotNet/Extensions/Statistics/Variations.cs
  src/MatrixDotNet/Matrix.cs
  tests/MatrixDotNet.UnitTesting/MatrixTests/CriteriesTests/SylvestersCriterionTests.cs
  tests/MatrixDotNet.UnitTesting/MatrixTests/DeterminantTest.cs
  tests/MatrixDotNet.UnitTesting/MatrixTests/MatrixExtensionTest.cs
  tests/MatrixDotNet.UnitTesting/MatrixTests/MatrixTest.cs
  tests/MatrixDotNet.UnitTesting/MatrixTests/MulVecByMatrix.cs
  tests/MatrixDotNet.UnitTesting/MatrixTests/StatisticsTests/StatisticsTests.cs
Labels: new

#37 Optimize equals and add random for byte
  src/MatrixDotNet/Extensions/Builder/MatrixRandomExtension.cs
  src/MatrixDotNet/Matrix.cs
  src/MatrixDotNet/NotStableFeatures/UnsafeEqualsUnrolled.cs
  tests/MatrixDotNet.PerformanceTesting/Matrix/EqualsBench.cs
  tests/MatrixDotNet.UnitTesting/MatrixTests/MatrixTest.cs
Labels: enhancement, new

#45 Update docs
  .github/workflows/build_docs.yml
  docs/api/index.md
  docs/articles/features/getting_started.md
  docs/articles/features/statistics.md
  docs/articles/features/toc.yml
  docs/articles/guides/Strassen.md
  docs/articles/guides/absorption.md
  docs/articles/guides/access.md
  docs/articles/guides/bitwise.md
  docs/articles/guides/conversion.md
  docs/articles/guides/sorting.md
  docs/articles/guides/toc.yml
  docs/articles/intro.md
  docs/articles/license.md
  docs/articles/toc.yml
  docs/docfx.json
  docs/images/MatrixDotNet.png
  docs/images/MatrixDotNet_128x128.png
  docs/images/logo/m.svg
  docs/images/logo/matrix.ico
  docs/images/logo/matrix.svg
  docs/images/logo/matrix_40x40.png
  docs/index.md
  docs/toc.yml
Labels: documentation

#47 Update README.md
  README.md
Labels: documentation

#53 Update docs
  .github/workflows/build_docs.yml
  .github/workflows/run_tests.yml
  docs/articles/guides/absorption.md
  docs/articles/intro.md
  docs/index.md
  samples/Samples/Parser.cs
  samples/Samples/Program.cs
  samples/Samples/SampleRunner.cs
  samples/Samples/SampleTest.cs
  samples/Samples/Samples.csproj
  samples/Samples/Samples/GaussSolveSample.cs
  samples/Samples/Samples/MatrixComplexSamples/CreateMatrixComplex.cs
  samples/Samples/Samples/MatrixSamples/AbsorptionSample.cs
  samples/Samples/Samples/MatrixSamples/LUPSample.cs
  samples/Samples/Samples/MatrixSamples/LUSample.cs
  samples/Samples/Samples/MatrixSamples/MatrixCreateSample.cs
  samples/Samples/Samples/MatrixSamples/SimpleOperations.cs
  samples/Samples/Samples/SimpleOperations.cs
  samples/Samples/Samples/StatisticsSample.cs
  samples/Samples/Samples/StrassenSample.cs
  samples/Samples/Samples/VectorSamples/CreateVectorSample.cs
  samples/Samples/Samples/VectorSamples/VectorSimpleOperations.cs
  src/MatrixDotNet/Vector.cs
  tests/MatrixDotNet.FunctionalTesting/MatrixDotNet.FunctionalTesting.csproj
  tests/MatrixDotNet.PerformanceTesting/MatrixDotNet.PerformanceTesting.csproj
  tests/MatrixDotNet.UnitTesting/MatrixDotNet.UnitTesting.csproj
Labels: docfx, documentation

#42 Optimize dot product of vector, min and max of matrix
  src/MatrixDotNet.Math/BitwiseGeneric.cs
  src/MatrixDotNet.Math/BitwiseGenericSingle.cs
  src/MatrixDotNet.Math/MathGeneric.cs
  src/MatrixDotNet.Math/MathGenericSingle.cs
  src/MatrixDotNet/Extensions/Statistics/Intervals.cs
  src/MatrixDotNet/Extensions/Statistics/Maximum.cs
  src/MatrixDotNet/Extensions/Statistics/Minimum.cs
  src/MatrixDotNet/Extensions/Statistics/Variations.cs
  src/MatrixDotNet/Matrix.cs
  src/MatrixDotNet/MatrixComplex.cs
  src/MatrixDotNet/Vector.cs
  src/MatrixDotNet/VectorOperator.cs
  tests/MatrixDotNet.UnitTesting/MatrixTests/StatisticsTests/BitMatrixExtensionTest.cs
  tests/MatrixDotNet.UnitTesting/VectorTests/VectorBasicTest.cs
  tests/MatrixDotNet.UnitTesting/VectorTests/VectorOperationTest.cs
Labels: enhancement
